// Generated by CoffeeScript 1.6.3
(function() {
  var description, descriptions, longForm, pitCode, pitCodes, pitSize, sentence, webPage, _i, _len;

  descriptions = ["J1", "J2", "J3", "J4", "J5", "J8", "J9", "H1", "H2", "H4", "H5", "H3", "H8", "H9", "P1", "P2", "P3", "P4", "P5", "P8", "P9", "1", "2", "3", "4", "6", "7", "8", "C6", "C8", "C9", "Vic D", "MH - Footway", "MH - Roadway", "A", "B", "C", "D", "0", "X - Other"];

  pitCodes = {
    "J": "Injection Moulded",
    "H": "Hand Moulded",
    "P": "Thermoplastic",
    "PC": "Precast"
  };

  webPage = [];

  if (typeof document !== "undefined" && document !== null) {
    webPage.push("<h2>Specification ID</h2>");
    webPage.push("<a href='./specID.coffee'>Source Code Used To Generate Result</a>");
    webPage.push("<table class='table table-striped' width='200px'>");
    webPage.push("<tr><th>Description</th><th>Sentence</th></tr>");
  }

  for (_i = 0, _len = descriptions.length; _i < _len; _i++) {
    description = descriptions[_i];
    pitSize = description[description.search(/\d/)];
    pitCode = description[0];
    if ((pitSize != null) && pitCode === "C") {
      pitCode = "PC";
    }
    if (pitCode === "V") {
      pitSize = "D";
    }
    if (pitCode === "0") {
      pitCode = "O";
    }
    longForm = pitCodes[pitCode];
    switch (pitCode) {
      case "H":
      case "J":
      case "P":
      case "PC":
        sentence = "Pit " + pitSize + ", " + pitCode + " (" + longForm + ")";
        break;
      case "V":
        sentence = "Pit D, H (Hand Moulded - Vic)";
        break;
      case "M":
        sentence = description.replace("MH", "Manhole");
        break;
      case "X":
        sentence = "Other";
        break;
      default:
        sentence = "Pit " + pitCode + ", H (Hand Moulded)";
    }
    if (typeof document !== "undefined" && document !== null) {
      webPage.push("<tr><td>" + description + "</td><td>" + sentence + "</td></tr>");
    }
    if (typeof root !== "undefined" && root !== null) {
      console.log("" + description + "\t" + sentence);
    }
  }

  if (typeof document !== "undefined" && document !== null) {
    webPage.push("</table>");
    document.getElementById('specID').innerHTML = webPage.join("");
  }

}).call(this);
