// Generated by CoffeeScript 1.6.3
(function() {
  var codedValues, csv, fs;

  if (typeof root !== "undefined" && root !== null) {
    /*
    Converts a csv definition of the Coded Values Schema to a
    Javascript Object
    
    This file runs on the server via node.js and generates
    a javascript file called codedValues.js.
    This script attached an object to the DOM called codedValues
    that can then be interacted with via other scripts.
    */

    fs = require("fs");
    csv = require("csv");
    codedValues = {};
    fs = require("fs");
    csv = require("csv");
    codedValues = {};
    csv().from.stream(fs.createReadStream("../csv/codedValues.csv")).on('record', function(row, index) {
      if (codedValues[row[0]] === void 0) {
        codedValues[row[0]] = {};
      }
      codedValues[row[0]][row[1]] = [row[2]];
      return codedValues[row[0]][row[1]] = codedValues[row[0]][row[1]].toString().replace("?", "^2");
    }).on('end', function(count) {
      var codedValuesCoffee, json;
      console.log(codedValues);
      json = JSON.stringify(codedValues);
      /*
      generate coffeescript file to make the json accessible
      to the DOM
      */

      codedValuesCoffee = "if window?\n  json = '" + json + "'\n  window.codedValues = JSON.parse(json)";
      fs.writeFile("./codedValues.coffee", codedValuesCoffee, function(err) {
        if (err) {
          return console.log(err);
        } else {

        }
      });
      return console.log("The file was saved!");
    });
  }

}).call(this);
